name: release
on: [workflow_dispatch]
# on:
#   push:
#     tags:
#       - 'v*'

jobs:
  tag:
    name: tag
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && !github.event.repository.fork }}
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: install-node
        uses: actions/setup-node@master

      - name: semantic-release-prerequisites
        run: |
          npm install --no-package-lock --no-save \
            @semantic-release/commit-analyzer \
            @semantic-release/release-notes-generator \
            @semantic-release/changelog \
            @semantic-release/exec \
            @semantic-release/git \
            conventional-changelog-conventionalcommits

      # - name: semantic-release-dry-run
      #   run: npx semantic-release --ci --dry-run
      #   if: ${{ github.event.repository.fork }}

      - name: semantic-release
        run: npx semantic-release --ci
        if: ${{ !github.event.repository.fork }}
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}

  goreleaser:
    name: release
    needs: [tag]
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2.3.4

      - name: unshallow
        run: git fetch --prune --unshallow

      - name: set up go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: import gpg key
        id: import_gpg
        uses: hashicorp/ghaction-import-gpg@v2.1.0
        env:
          # These secrets will need to be configured for the repository:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}

      - name: run goreleaser
        uses: goreleaser/goreleaser-action@v2.5.0
        with:
          version: latest
          args: release --rm-dist
        env:
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          # GitHub sets this automatically
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
